POST http://localhost:3001/auth/signup
Content-Type: application/json

{
  "birthdate": "1995-01-01",
  "maternalSurname": "ex mat",
  "paternalSurname": "ex pat",
  "name": "example name",
  "email": "example13@example.com",
  "password": "Hola123#",
  "genderId": "a1b6195a-1e89-4517-8f6d-2acc7ce04530",
  "ipAddress": "192.168.0.2",
  "userAgent": "Mozilla/5.0 (Windows NT 10.0 Win64 x64 rv:89.0) Gecko/20100101 Firefox/89.0"
}

POST http://localhost:3001/auth/signin
Content-Type: application/json

{
  "email": "pxndxs@pxndxs.com",
  "password": "Hola123#",
  "ipAddress": "192.168.0.2",
  "userAgent": "Mozilla/5.0 (Windows NT 10.0 Win64 x64 rv:89.0) Gecko/20100101 Firefox/89.0"
}

POST http://localhost:3001/auth/signin
Content-Type: application/json

{
  "email": "example13@example.com",
  "password": "Hola123#",
  "ipAddress": "192.168.0.2",
  "userAgent": "Mozilla/5.0 (Windows NT 10.0 Win64 x64 rv:89.0) Gecko/20100101 Firefox/89.0"
}
