POST http://localhost:3001/auth/signup
Content-Type: application/json

{
  "birthdate": "1995-01-01",
  "maternalSurname": "ex mat",
  "paternalSurname": "ex pat",
  "name": "example name",
  "email": "example15@example.com",
  "password": "Hola123#",
  "genderId": "b78ec694-6435-455b-9665-0532b245ea51"
}

POST http://localhost:3001/auth/signin
Content-Type: application/json

{
  "email": "pxndxs@pxndxs.com",
  "password": "Hola123#"
}

POST http://localhost:3001/auth/signin
Content-Type: application/json

{
  "email": "example13@example.com",
  "password": "Hola123#"
}
