export { UsersModule } from './users/users.module'
export { PeopleInfoModule } from './people-info/people-info.module'
export { UserAvatarsModule } from './user-avatars/user-avatars.module'
export { RolesModule } from './roles/roles.module'
export { SessionsModule } from './sessions/sessions.module'
export { UserPhonesModule } from './user-phones/user-phones.module'
export { UserAddressesModule } from './user-addresses/user-addresses.module'
export { UserCreditCardsModule } from './user-credit-cards/user-credit-cards.module'
